"""create projects table

Revision ID: 638f89fe8caa
Revises: c4da0dea5b97
Create Date: 2026-10-07 22:52:48.974024

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "638f89fe8caa"
down_revision: str | Sequence[str] | None = "c4da0dea5b97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("date", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("bullet_intro", sa.Text(), nullable=False),
        sa.Column("bullets", sa.JSON(), nullable=False),
        sa.Column("demo_url", sa.String(length=200), nullable=True),
        sa.Column("github_url", sa.String(length=200), nullable=True),
        sa.Column("image_url", sa.String(length=200), nullable=True),
        sa.Column("featured_image_url", sa.String(length=200), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=False),
        sa.Column("more_tech_count", sa.String(length=100), nullable=True),
        sa.Column("highlights", sa.JSON(), nullable=False),
        sa.Column("completedModules", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
