"""create projects table

Revision ID: 9d8919876af9
Revises: ef6b92cb5397
Create Date: 2026-10-08 11:33:10.598830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8919876af9'
down_revision: Union[str, Sequence[str], None] = 'ef6b92cb5397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('bullet_intro', sa.Text(), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('demo_url', sa.String(length=200), nullable=True),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('featured_image_url', sa.String(length=200), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=False),
    sa.Column('more_tech_count', sa.String(length=100), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('completedModules', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
