"""creates education table

Revision ID: ef6b92cb5397
Revises: 5729b9c399f5
Create Date: 2026-10-07 18:54:14.967419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef6b92cb5397"
down_revision: str | Sequence[str] | None = "5729b9c399f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("degree", sa.String(), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_education_id"), "education", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_education_id"), table_name="education")
    op.drop_table("education")
    # ### end Alembic commands ###
